services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - JELLYFIN_PublishedServerUrl=10.0.0.2
    volumes:
      - jellyfin_data:/config
      - jellyfin_tvshows:/data/tvshows
      - jellyfin_movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
volumes:
  jellyfin_data:
    name: jellyfin_data
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/mnt/notonedrive/docker-volumes/jellyfin
  jellyfin_tvshows:
    name: jellyfin_tvshows
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/mnt/notonedrive/media/tvshows
  jellyfin_movies:
    name: jellyfin_movies
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/mnt/notonedrive/media/movies
networks: {}
